a = int(input("Nhập số a: "))
b = int(input("Nhập số b: "))

print("a cộng b:", a + b)
print("a trừ b:", a - b)
print("a nhân b:", a * b)
print("a chia lấy nguyên b:", a // b)
print("a mũ b:", a ** b)
print("a chia dư b:", a % b)
print("a so với b:", "lớn hơn" if a > b else "nhỏ hơn" if a < b else "bằng")
print("a AND b:", a & b)
print("a OR b:", a | b)
print("a XOR b:", a ^ b)
print("NOT a == b:", not (a == b))
print("a >> 1 đơn vị:", a >> 1)
print("a << 1 đơn vị:", a << 1)
